version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        ClusterName: MyCluster        # Replace with your actual ECS cluster name
        ServiceName: my-service       # Replace with your actual ECS service name
        TaskDefinition: "imagedefinitions.json"
        LoadBalancerInfo:
          ContainerName: my-container
          ContainerPort: 8085
